import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/Navbar";
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "@/context/CartContext"; // 👈 ajoute ça

export const metadata: Metadata = {
  title: "Solidarigo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" className={`${geist.variable}`}>
      <body>
        <SessionProvider>
          <CartProvider> {/* ✅ ENTOURE ici */}
            <Navbar />
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
